/*
 * Decompiled with CFR 0.151.
 */
package net.runelite.client.plugins.xrunedragons;

public enum XRuneDragonsState {
    MOVING,
    TIMEOUT,
    FIND_BANK,
    DEPOSIT_ITEMS,
    EAT_FOOD,
    WITHDRAW_COMBAT,
    WITHDRAW_DIVINE_COMBAT,
    WITHDRAW_SUPER_EXTENDED,
    WITHDRAW_EXTENDED,
    DRINK_COMBAT,
    WITHDRAW_RESTORES,
    WITHDRAW_TELES,
    WITHDRAW_FOOD,
    LOGOUT,
    DRINK_PRAYER,
    ATTACK_DRAGON,
    LOOT_ITEMS,
    IN_COMBAT,
    ACTIVATE_PRAY,
    DEACTIVATE_PRAY,
    DOWN_STAIRS,
    ENTER_DOOR,
    WALK_DOOR,
    ENTER_DRAGONS,
    TELE_HOME,
    TELE_LITH,
    TELE_EDGE,
    DRINK_POOL,
    DRINK_ANTIFIRE,
    WITHDRAW_ITEMS,
}